CPI average prices
datawookie/saffer pull request #11
Opened 2021-01-19 14:33 UTC by Vusani3

2021-01-20 13:03 UTC, datawookie requested changes

2021-01-20 13:03 UTC, datawookie commented on R/unemployment-worldbank-create.R
> +  unemployment_data <- data.frame(Year = as.numeric(x),  "Unemployment_rate" = y)
Rather use all lowercase for column names.

2021-01-21 03:23 UTC, datawookie requested changes

2021-01-21 03:23 UTC, datawookie commented on R/unemployment-education.R
> +#' @format A data frame with 5 variables:
I could only four column names.

2021-01-21 03:23 UTC, datawookie commented on R/unemployment-education.R
> +#' @format A data frame with 5 variables:
I only see four column names.

2021-01-21 03:23 UTC, datawookie commented on R/unemployment-gender.R
> +#' @format A data frame with 5 variables:
I only see four column names.

2021-01-21 03:23 UTC, datawookie commented on R/unemployment-education.R
> +#'  \item{Education}
Please use lower case for column names.

2021-01-21 03:23 UTC, datawookie commented on R/unemployment-gender.R
> +#'  \item{Gender}
Please use lower case for column names.

2021-01-21 03:23 UTC, datawookie commented on data-raw/unemployment_education.csv
> +#http://www.statssa.gov.za/publications/P0211/P02113rdQuarter2020.pdf
- Please insert space between `#` and `http`.
- The second line should either be deleted or start with a `#`.

2021-01-21 03:23 UTC, datawookie commented on data-raw/unemployment_gender.csv
> +#http://www.statssa.gov.za/publications/P0211/P02113rdQuarter2020.pdf
- Please insert space between `#` and `http`.
- The second line should either be deleted or start with a `#`.

2021-01-21 03:23 UTC, datawookie commented on scripts/create-unemployment-education.R
> +unemployment_education <- read_delim(file.path(
Does this alignment look good to you?

How about this:

```r
unemployment_education <- read_delim(
    file.path(
        "data-raw",
        "unemployment_education.csv"
    ),
    delim = ";"
)
```

Isn't that easier to read?

Come on, @Vusani3!

2021-01-21 03:23 UTC, datawookie commented on scripts/create-unemployment-gender.R
> +unemployment_gender <- read_delim(file.path("data-raw",
See previous comment.

2021-01-21 03:23 UTC, datawookie commented on scripts/create-unemployment-education.R
Have you run this file to check that it works with the data? I don't think so!

Because when I run the script it only extracts a single column from the CSV.

🚨 Please don't submit a merge request with work that you have not tested yourself. This just wastes my time.

FYI you need to tell `read_delim()` that `#` is being used as the comment character.

2021-01-21 07:26 UTC, datawookie requested changes

2021-01-21 07:26 UTC, datawookie commented on data-raw/unemployment_gender.csv
> +gender ;year;quarter ;unemployment rate
Are the spaces here intentional?

2021-01-21 07:26 UTC, datawookie commented on scripts/create-unemployment-education.R
I see that you are using `skip` here. This is not a very good solution. What happens if you insert another line of comments. Sure it would be better to use the `comment` option like I suggested above?

2021-01-21 07:26 UTC, datawookie commented on scripts/create-unemployment-education.R
Please also rather be explicit about the semi-colon by having `delim = ";"`.

2021-01-21 07:26 UTC, datawookie commented on scripts/create-unemployment-education.R
>  library(dplyr)
Do we actually use `{dplyr}` here?

2021-01-21 07:26 UTC, datawookie commented on scripts/create-unemployment-gender.R
>  library(dplyr)
Do we actually use `{dplyr}` here?

2021-01-21 07:26 UTC, datawookie commented on scripts/create-unemployment-gender.R
> +    "unemployment_gender.csv"
For consistency with other files in the `data-raw/` folder, please use hyphens rather than underscores in file names.

2021-01-21 07:26 UTC, datawookie commented on scripts/create-unemployment-education.R
> +    "unemployment_education.csv"
For consistency with other files in the `data-raw/` folder, please use hyphens rather than underscores in file names.

2021-01-21 09:58 UTC, datawookie requested changes

2021-01-21 09:58 UTC, datawookie commented on scripts/create-cpi-averageprices-urban.R
> +# Loading Packages --------------------------------------------------------
The formatting of this file is inconsistent with the rest of the files. Please sort out commenting and indentation.

2021-01-21 09:58 UTC, datawookie commented on scripts/create-cpi-averageprices-urban.R
> +usethis::use_data(cpi_averageprices, overwrite = TRUE)
The column names in the resulting data frames are not acceptable. Should never have spaces or punctuation. Preferably lowercase too. You can use `janitor::clean_names()` to sort this out to some extent. But handle the pivoting issue (below) first!

Also a lot of these data are "wide". For instance, the urban data has dates for columns. These data should be pivoted.

2021-01-21 09:58 UTC, datawookie commented on scripts/create-unemployment-education.R
> +usethis::use_data(unemployment_education, overwrite = TRUE)
Did you look at the data being produced by this script?

2021-01-21 09:58 UTC, datawookie commented on scripts/create-unemployment-gender.R
> +usethis::use_data(unemployment_gender, overwrite = TRUE)
Did you look at the data being produced by this script?

2021-01-21 09:58 UTC, datawookie commented on scripts/unemployment-worldbank-create.R
> +library(httr)
I think that this is a cleaner implementation:

```
library(httr)
library(purrr)

result <- GET('https://api.worldbank.org/v2/countries/ZA/indicators/SL.UEM.TOTL.ZS?per_page=10000&format=JSON')

content <- content(result)

metadata <- content[[1]]
data <- content[[2]]

extract_data_year <- function(datum) {
  tibble(
    country_id = datum$country$id,
    country_iso3 = datum$countryiso3code,
    country_name = datum$country$value,
    year = as.integer(datum$date),
    unemployed_percent = ifelse(is.null(datum$value), NA, datum$value)
  )
}

unemployment_sa <- map_dfr(data, extract_data_year) %>%
  filter(!is.na(unemployed_percent))

usethis::use_data(unemployment_sa, overwrite = TRUE)
```

2021-01-21 12:27 UTC, datawookie commented on data-raw/fuel-price-usd-exchange-rate.csv
> +1986,Jan,2.3563
It looks like this file has got a lot smaller. Where did the data go?

2021-01-21 14:21 UTC, datawookie commented on data-raw/fuel-price-usd-exchange-rate.csv
> +1986,Jan,2.3563
I still don't understand where the data has gone. Please can you help me understand?

2021-01-21 15:46 UTC, Vusani3 commented on data-raw/fuel-price-usd-exchange-rate.csv
> +1986,Jan,2.3563
From my side there are 290 observations. I just ran the script for fuel-price

2021-01-21 15:53 UTC, datawookie commented on data-raw/fuel-price-usd-exchange-rate.csv
> +1986,Jan,2.3563
Did you look at the diffs in the merge request?

This is the current file: https://github.com/datawookie/saffer/blob/bdcbca0fd2868564db1b01af0d9206db8e64a90f/data-raw/fuel-price-brent-crude.csv. It has 193 records.

This is the file that you want to merge over it: https://github.com/Vusani3/saffer/blob/5bc58d6f6ff8140db95be6647378d2b506f33562/data-raw/fuel-price-brent-crude.csv. It has only 61 records.

Where did all the other data go? Please just look at this with a critical eye like a scientist. 132 records have just disappeared. Where did they go? Is the old data correct? Is the new data correct? Why?

2021-01-21 17:31 UTC, merged

2021-01-21 17:31 UTC, datawookie commented
Wow, that was pretty epic.