Update pkg docs 📝
datawookie/saffer pull request #9
Opened 2021-01-17 14:55 UTC by jonmcalder

For some reason I happened to spot your recent commits, and given that I'm somehow listed as a pkg co-author for having done little more than contribute some documentation and a hex logo, I figured I better pull my weight. So here are some more documentation updates 🤣 

- Add missing documentation for `fuel_price_usd_exchange_rate` & `fuel_price_brent_crude`
- Add missing LICENSE file
- Add basic pkgdown config (just need to enable GitHub pages and run `usethis::use_github_action("pkgdown")` to setup the relevant GHA)

2021-01-18 15:11 UTC, datawookie requested changes
Hi John,

Thanks for this. We're actually actively using the data from this package now, hence the renewed enthusiasm.

Thanks very much for your contribution. I've made one minor request (removing a period for consistency).

Also, I'd like to suggest that we set this up to use Travis to build the pkgdown site. I've used this on a few other packages and it's very convenient. If you'd like to put that in place, that'd be cool. Otherwise I'd be happy to hook it up.

Thanks, Andrew.

2021-01-18 15:11 UTC, datawookie commented on R/fuel-price-used-exchange-rate.R
> +#' Exchange rate history for the South African Rand against the US Dollar.
Please remove period from end of line.

2021-01-18 22:04 UTC, jonmcalder commented on R/fuel-price-used-exchange-rate.R
> +#' Exchange rate history for the South African Rand against the US Dollar.
Ok sure - some of the existing titles had trailing periods and some were without, so I've removed them across the board for consistency.

2021-01-18 22:08 UTC, jonmcalder commented
Nice! I thought you might be making use of it - that's great.

Re setting up the pkgdown site, are you aware that Travis has been acquired by a private company and is discontinuing their free / open source tier? See here for more info: https://ropensci.org/technotes/2020/11/19/moving-away-travis/

Either way, it's your repo and I don't have sufficient permissions so I'll leave it to you to setup the CI.

2021-01-19 04:08 UTC, datawookie commented on R/fuel-price-used-exchange-rate.R
> +#' Exchange rate history for the South African Rand against the US Dollar.
Thanks, @jonmcalder. Yup, this is an artefact of having a few people hacking on this. Thanks for cleaning it all up! :+1:

2021-01-19 04:09 UTC, datawookie commented
Yup, I'm aware of the issues with Travis. Going to take the route of least resistance for the moment but certainly will look at a more durable approach later on.

2021-01-19 04:41 UTC, merged